package switcher;

import org.apache.camel.Consume;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.util.concurrent.atomic.AtomicBoolean;

/**
 * @author Ryan Gardner
 * @date 3/26/15
 */
@Component
@Profile("!raspberryPi")
public class FakeHardware implements WaverStatus {

    private AtomicBoolean waverStatus = new AtomicBoolean(false);

    @Override
    public boolean isWaverOn() {
        return waverStatus.get();
    }

    private static final Logger log = LoggerFactory.getLogger(FakeHardware.class);

    @Consume(uri = "seda:turnOnWaver")
    public void turnOnWaver() {
        if (waverStatus.compareAndSet(false, true)) {
            System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMM~M7MMIZM=:MMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMM,I7D$8OZIMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM77?Z+I7+==MMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMI$7O7O+MMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM$$OO$7ZZMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMM$7ZZ$$ZMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMIMMMMMMMMMMMMMMMMMMIIIIIII78MMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMZ7$~MMMMMMMMMMMMMMMZZ$7I7$$ZO8MMMMMMMMMMMMMMMM777MMMMMM\n" +
                    "MMMMMMO$7$MMMMMMMMMMMMMMZZ$7II7$ZODMMMMMMMMMMMMMMMIIZOMMMMMM\n" +
                    "MMMMMMMO$I$MMMMMMMMMMMMMZZ$7II7$ZOZMMMMMMMMMMMMN77I$OMMMMMMM\n" +
                    "MMMMMMMMO$I7OMMMMMMMMMMMZ$$7~I7$=ZDMMMMMMMMMMMMI?$ZDMMMMMMMM\n" +
                    "MMMMMMMMMZ$II7MMMMMMMMMMZ$$.8~$~MZZMMMMMMMMMM?I?$OMMMMMMMMMM\n" +
                    "MMMMMMMMMMMZ7I7MMMMMMMMMZZ$7$7778OZMMMMMMMMMII7$OMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMZ7?IIMMMMMMMZZ$7II7$ZOZMMMMMMM?I?7ZIMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMO$II7MMMMMMZZ$,II$$$ZZMMMMMMIII$ZMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMZ$7I7MMMMMZZZ$:,:~~OZMMMMMI?7ZOMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMM+Z7?7?MMMZZZ$II$$ZO$MMM+II$O$MMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMO$I7$MMZZZ$I?7$$OZMMII7ZOMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMM8Z$I7+OZZ$I?7$ZOOZ7?$ZOMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMM?Z$I7I777II7$ZZZI7$Z$MMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMZ$7I$$7II7$ZZO$OOMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMO8$OZ$II7$ZOOZIMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMOOZ$7I$~ZZ8MMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM7+Z$I7ZIZZ8MMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM$Z$,7?7$ZZOMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMO$Z$I7$:OOOMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM+$Z$7I7$$ZOMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM,ZZ,7I7$$O$MMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM.+Z$7I7,?ZZMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM,ZZ77II7IZOMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM.ZZ,7?7$$O$MMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM,:ZZ7I7,,$ZMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM8ZZ$7I77$ZZMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM+I77II$Z$ZMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM~~~~~~$ZOOMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM~~~~::7ZZZMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM~~~~~~$ZZOMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=~~~:~$ZZOMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=~~~~~7ZZO,MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=~~~~~7ZZZ,MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=~~~~~7$ZZ,MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~:~~7$ZZ,MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=~~==~7$ZZ:MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=~~~~~7$ZZ~MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~~~~7$ZZ+MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~~~~7$ZZIMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~~:~7$ZZ7MMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM+=~~~~$$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM+=~~~~7$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM+=~~~~7$ZZOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~~~~7$ZZOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM+=~~~~7$ZZOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~~~~I$ZZOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~~~~?$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM==~~~~+$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=~=:~~=$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM===~~~~$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM===~~~~$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM===~~~~$ZZZMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM===~~~:$ZZOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM=====~:ZZZOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM+=====:$OOOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMM?==~~~,$ZZOMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMMNNDDDDNNNNMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMMNDNDDDNNNNMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMMMNNDDDNNNN:MMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMNNDNDDDDDNNMDMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMNNDNDDDNNDNMNMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMODDNNDDDNNDNNMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMM:8DDNDDDDNDDDDMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMDNNDNN8NNNNNNNNMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMNMMM8NONDMMMM?$MMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD=MMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        }

    }

    @Consume(uri = "seda:turnOffWaver")
    public void turnOffWaver() {
        if (waverStatus.compareAndSet(true, false)) {
            System.out.println("  DEFLATED! \n" +
                    " \n" +
                    " .====._---->_--->...");
        }
    }

}
